# スクリプトデータ
# セリフを編集後、npm run sync-script で反映

- id: 1
  character: zundamon
  text: みんなー！MBSラジオで放送中の「まいどおおきに！！アッパレでーす！」を紹介するのだ！
  displayText: みんなー！MBSラジオで放送中の「まいどおおきに！！Appare!でーす！」を紹介するのだ！
  scene: 1
  pauseAfter: 15
  visual:
    type: text
    text: "MBSラジオ\n「まいどおおきに！！Appare!でーす！」"
    fontSize: 60
    color: "#ffffff"
    animation: zoomIn

- id: 2
  character: gaoyan
  text: そうね。アイドルグループ「アッパレ」のメンバーが、賑やかにお送りするトーク番組よ。
  displayText: そうね。アイドルグループ「Appare!」のメンバーが、賑やかにお送りするトーク番組よ。
  scene: 1
  pauseAfter: 15

- id: 3
  character: zundamon
  text: 新メンバー3人が加わって9人体制になったアッパレの、ラジオでしか聞けない素顔がたっぷりなのだ！
  displayText: 新メンバー3人が加わって9人体制になったAppare!の、ラジオでしか聞けない素顔がたっぷりなのだ！
  scene: 1
  pauseAfter: 10

- id: 4
  character: gaoyan
  text: 毎週の放送、私たちと一緒にチェックしていきましょう。
  scene: 1
  pauseAfter: 30
